#!/bin/sh

HOME="$(dirname -- "$(readlink -f -- "${0}")" )"

JAVA=java
JAR=$(echo ${HOME}/target/RemoteLocator-*-jar-with-dependencies.jar )
CONFIG=${HOME}/irdb.xml

cd $HOME
exec "${JAVA}" -cp "${JAR}" org.harctoolbox.remotelocator.RemoteDatabase -o "${CONFIG}" --sort --irdb ../irdb/codes
