#!/bin/sh

HOME="$(dirname -- "$(readlink -f -- "${0}")" )"

JAVA=java
JAR=$(echo ${HOME}/target/RemoteLocator-*-jar-with-dependencies.jar )
CONFIG=${HOME}/girrlib.xml

cd $HOME
exec "${JAVA}" -jar "${JAR}" -c "${CONFIG}" --sort --girrdir ../GirrLib/Girr
