#!/bin/sh

HOME="$(dirname -- "$(readlink -f -- "${0}")" )"

JAVA=java
JAR=$(echo ${HOME}/target/RemoteLocator-*-jar-with-dependencies.jar )
CONFIG=${HOME}/remotelocator.xml

rm "${CONFIG}"
cd $HOME
exec time "${JAVA}" -jar "${JAR}" -.config "${CONFIG}" --sort \
     --girrdir ../GirrLib/Girr \
     --irdb ../irdb/codes \
     --lirc ../../lirc/lirc-remotes/remotes \
     --jp1 src/test/jp1/jp1-master-1.16.fods
