#!/bin/sh

HOME="$(dirname $(dirname -- "$(readlink -f -- "${0}")" ))"

#UPLOAD="curl --netrc --upload-file"
UPLOAD=upload

upload () {
    echo Now upload $1 to $2.
}

FTPDIR="ftp://bengt-martensson.de/harctoolbox/downloads"
TIME=
JAVA=java
JAR=$(echo ${HOME}/target/RemoteLocator-*-jar-with-dependencies.jar )
CONFIG=${HOME}/remotelocator.xml
CLASS=org.harctoolbox.remotelocator.RemoteDatabase
STYLESHEET=${HOME}/src/main/xslt/remotelocator2html.xsl
JP1FILE=${HOME}/src/test/jp1/jp1-master-1.17.fods
HTML=${HOME}/remotelocator.html
XSLTPROC=xsltproc

rm -f "${CONFIG}" "${HTML}"
cd $HOME
${TIME} "${JAVA}" -cp "${JAR}" "${CLASS}" \
    --out "${CONFIG}" --sort \
    --girrdir ../GirrLib/Girr \
    --irdb ../irdb/codes \
    --lirc ../../lirc/lirc-remotes/remotes \
    --jp1 "${JP1FILE}"

${XSLTPROC}  -o "${HTML}" "${STYLESHEET}"  "${CONFIG}"

${UPLOAD} remotelocator.xml  ${FTPDIR}/remotelocator.xml
${UPLOAD} remotelocator.html ${FTPDIR}/remotelocator.html
